use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::collections::{HashMap, HashSet};
use petgraph::graph::{DiGraph, NodeIndex};
use petgraph::algo::toposort;
use petgraph::visit::EdgeRef;

use crate::orchestration::Task;

/// Context provided to the planner for generating task plans
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlannerContext {
    /// Available agent types that can be assigned to tasks
    pub available_agents: Vec<AgentType>,
    /// Resource constraints for the orchestration
    pub resource_constraints: ResourceConstraints,
    /// Existing tasks and their status (for replanning scenarios)
    pub existing_tasks: Vec<Task>,
    /// Additional context or requirements
    pub additional_context: HashMap<String, Value>,
}

/// Types of agents available for task assignment
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentType {
    pub name: String,
    pub capabilities: Vec<String>,
    pub model: String,
    pub description: String,
}

/// Resource constraints for planning
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceConstraints {
    /// Maximum number of concurrent tasks
    pub max_concurrent_tasks: usize,
    /// Maximum time allowed for the entire orchestration (in seconds)
    pub max_duration_seconds: Option<u64>,
    /// Available computational resources
    pub available_memory_gb: Option<f64>,
    pub available_cpu_cores: Option<usize>,
}

/// A structured task plan generated by the planner
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskPlan {
    /// The original goal that was decomposed
    pub goal: String,
    /// List of tasks in the plan
    pub tasks: Vec<PlannedTask>,
    /// Dependencies between tasks (task_id -> list of dependency task_ids)
    pub dependencies: HashMap<String, Vec<String>>,
    /// Estimated total duration in seconds
    pub estimated_duration_seconds: Option<u64>,
    /// Estimated resource requirements
    pub resource_requirements: ResourceRequirements,
    /// Success criteria for the overall plan
    pub success_criteria: Vec<String>,
    /// Metadata about the plan
    pub metadata: PlanMetadata,
}

/// A task within the plan
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlannedTask {
    /// Unique identifier for the task within this plan
    pub id: String,
    /// Human-readable name
    pub name: String,
    /// Detailed description of what the task should accomplish
    pub description: String,
    /// The specific goal/prompt for this task
    pub goal: String,
    /// Suggested agent type for this task
    pub suggested_agent: String,
    /// Expected inputs from parent tasks
    pub expected_inputs: Vec<ExpectedInput>,
    /// Expected outputs/artifacts this task will produce
    pub expected_outputs: Vec<ExpectedOutput>,
    /// Estimated duration in seconds
    pub estimated_duration_seconds: Option<u32>,
    /// Priority level (1-10, higher is more important)
    pub priority: u8,
    /// Whether this task can be retried on failure
    pub retriable: bool,
    /// Success criteria specific to this task
    pub success_criteria: Vec<String>,
}

/// Expected input from a parent task
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpectedInput {
    pub name: String,
    pub input_type: String,
    pub from_task_id: String,
    pub description: String,
}

/// Expected output from a task
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpectedOutput {
    pub name: String,
    pub output_type: String,
    pub description: String,
}

/// Resource requirements for the plan
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceRequirements {
    pub peak_memory_gb: Option<f64>,
    pub peak_cpu_cores: Option<usize>,
    pub total_compute_hours: Option<f64>,
}

/// Metadata about the plan
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanMetadata {
    pub created_at: DateTime<Utc>,
    pub planner_version: String,
    pub confidence_score: f32,
    pub alternative_approaches: Vec<String>,
    pub risks_and_mitigations: Vec<RiskMitigation>,
}

/// Risk and mitigation strategy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RiskMitigation {
    pub risk: String,
    pub impact: String,
    pub likelihood: String,
    pub mitigation: String,
}

/// The main planner agent
pub struct PlannerAgent {
    /// System prompt for the planner
    system_prompt: String,
    /// Model configuration
    model_config: ModelConfig,
}

/// Model configuration for the planner
#[derive(Debug, Clone)]
struct ModelConfig {
    model: String,
    temperature: f32,
    max_tokens: u32,
}

impl PlannerAgent {
    /// Create a new planner agent
    pub fn new() -> Self {
        let system_prompt = Self::build_system_prompt();
        let model_config = ModelConfig {
            model: "claude-3-opus-20240229".to_string(),
            temperature: 0.3,
            max_tokens: 4096,
        };

        Self {
            system_prompt,
            model_config,
        }
    }

    /// Generate a task plan from a high-level goal
    pub async fn plan_orchestration(&self, goal: &str, context: &PlannerContext) -> Result<TaskPlan> {
        // Build the planning request
        let planning_request = self.build_planning_request(goal, context)?;
        
        // Call Claude to generate the plan
        let plan_json = self.call_claude_for_planning(&planning_request).await?;
        
        // Parse the response into a TaskPlan
        let mut task_plan: TaskPlan = serde_json::from_value(plan_json)
            .context("Failed to parse task plan from Claude response")?;
        
        // Validate the plan
        self.validate_plan(&task_plan)?;
        
        // Optimize the plan
        self.optimize_plan(&mut task_plan)?;
        
        Ok(task_plan)
    }

    /// Validate a task plan
    pub fn validate_plan(&self, plan: &TaskPlan) -> Result<()> {
        // Check that all tasks have unique IDs
        let mut task_ids = HashSet::new();
        for task in &plan.tasks {
            if !task_ids.insert(&task.id) {
                anyhow::bail!("Duplicate task ID found: {}", task.id);
            }
        }

        // Validate dependencies
        for (task_id, deps) in &plan.dependencies {
            // Check that the task exists
            if !task_ids.contains(task_id) {
                anyhow::bail!("Dependency references non-existent task: {}", task_id);
            }
            
            // Check that all dependencies exist
            for dep in deps {
                if !task_ids.contains(dep) {
                    anyhow::bail!("Task {} depends on non-existent task: {}", task_id, dep);
                }
            }
        }

        // Check for circular dependencies
        if self.has_circular_dependencies(plan)? {
            anyhow::bail!("Circular dependencies detected in task plan");
        }

        // Validate task properties
        for task in &plan.tasks {
            if task.name.trim().is_empty() {
                anyhow::bail!("Task {} has empty name", task.id);
            }
            if task.goal.trim().is_empty() {
                anyhow::bail!("Task {} has empty goal", task.id);
            }
            if task.priority == 0 || task.priority > 10 {
                anyhow::bail!("Task {} has invalid priority: {}", task.id, task.priority);
            }
        }

        // Validate resource requirements
        if let Some(duration) = plan.estimated_duration_seconds {
            if duration == 0 {
                anyhow::bail!("Estimated duration cannot be zero");
            }
        }

        Ok(())
    }

    /// Optimize a task plan
    pub fn optimize_plan(&self, plan: &mut TaskPlan) -> Result<()> {
        // Sort tasks by priority and dependencies
        let sorted_order = self.topological_sort_with_priority(plan)?;
        
        // Reorder tasks based on optimal execution order
        let task_map: HashMap<String, PlannedTask> = plan.tasks
            .drain(..)
            .map(|t| (t.id.clone(), t))
            .collect();
        
        plan.tasks = sorted_order
            .into_iter()
            .filter_map(|id| task_map.get(&id).cloned())
            .collect();

        // Update metadata
        plan.metadata.planner_version = "1.0.0".to_string();
        plan.metadata.created_at = Utc::now();

        Ok(())
    }

    /// Build the system prompt for the planner
    fn build_system_prompt() -> String {
        r#"You are an expert task planner for an AI orchestration system. Your role is to decompose high-level goals into detailed, executable task graphs.

When given a goal, you must:

1. Analyze the goal and break it down into logical, atomic subtasks
2. Identify dependencies between tasks (which tasks must complete before others can start)
3. Suggest the most appropriate agent type for each task based on its requirements
4. Estimate resource requirements and duration for each task
5. Define clear success criteria for each task and the overall plan
6. Consider potential risks and suggest mitigation strategies

You must output a structured JSON task plan with the following schema:

{
  "goal": "The original goal",
  "tasks": [
    {
      "id": "unique_task_id",
      "name": "Human-readable task name",
      "description": "Detailed description of what this task accomplishes",
      "goal": "Specific prompt/goal for the agent executing this task",
      "suggested_agent": "agent_type",
      "expected_inputs": [
        {
          "name": "input_name",
          "input_type": "file|data|artifact",
          "from_task_id": "parent_task_id",
          "description": "What this input provides"
        }
      ],
      "expected_outputs": [
        {
          "name": "output_name",
          "output_type": "file|data|artifact",
          "description": "What this output contains"
        }
      ],
      "estimated_duration_seconds": 300,
      "priority": 8,
      "retriable": true,
      "success_criteria": [
        "Clear, measurable success criterion"
      ]
    }
  ],
  "dependencies": {
    "task_id": ["dependency_task_id1", "dependency_task_id2"]
  },
  "estimated_duration_seconds": 3600,
  "resource_requirements": {
    "peak_memory_gb": 8.0,
    "peak_cpu_cores": 4,
    "total_compute_hours": 2.5
  },
  "success_criteria": [
    "Overall success criterion for the entire plan"
  ],
  "metadata": {
    "confidence_score": 0.85,
    "alternative_approaches": [
      "Brief description of alternative approach"
    ],
    "risks_and_mitigations": [
      {
        "risk": "Description of potential risk",
        "impact": "high|medium|low",
        "likelihood": "high|medium|low",
        "mitigation": "How to mitigate this risk"
      }
    ]
  }
}

Guidelines:
- Task IDs should be descriptive and unique (e.g., "parse_requirements", "generate_tests")
- Each task should be atomic and have a single responsibility
- Dependencies should form a directed acyclic graph (no circular dependencies)
- Agent suggestions should match available agent types when provided
- Resource estimates should be realistic based on task complexity
- Success criteria must be specific and measurable
- Consider edge cases and failure modes in your planning

Focus on creating practical, executable plans that can be successfully orchestrated."#.to_string()
    }

    /// Build the planning request for Claude
    fn build_planning_request(&self, goal: &str, context: &PlannerContext) -> Result<String> {
        let mut request = format!("Please create a detailed task plan for the following goal:\n\n{}\n\n", goal);

        if !context.available_agents.is_empty() {
            request.push_str("Available agent types:\n");
            for agent in &context.available_agents {
                request.push_str(&format!(
                    "- {}: {} (capabilities: {})\n",
                    agent.name,
                    agent.description,
                    agent.capabilities.join(", ")
                ));
            }
            request.push_str("\n");
        }

        request.push_str("Resource constraints:\n");
        request.push_str(&format!(
            "- Max concurrent tasks: {}\n",
            context.resource_constraints.max_concurrent_tasks
        ));
        if let Some(duration) = context.resource_constraints.max_duration_seconds {
            request.push_str(&format!("- Max duration: {} seconds\n", duration));
        }
        if let Some(memory) = context.resource_constraints.available_memory_gb {
            request.push_str(&format!("- Available memory: {} GB\n", memory));
        }
        if let Some(cores) = context.resource_constraints.available_cpu_cores {
            request.push_str(&format!("- Available CPU cores: {}\n", cores));
        }

        if !context.existing_tasks.is_empty() {
            request.push_str("\nExisting tasks to consider:\n");
            for task in &context.existing_tasks {
                request.push_str(&format!(
                    "- {} ({}): {}\n",
                    task.name,
                    task.status,
                    task.description
                ));
            }
        }

        if !context.additional_context.is_empty() {
            request.push_str("\nAdditional context:\n");
            request.push_str(&serde_json::to_string_pretty(&context.additional_context)?);
        }

        Ok(request)
    }

    /// Call Claude to generate the plan (mock implementation)
    async fn call_claude_for_planning(&self, request: &str) -> Result<Value> {
        // In a real implementation, this would call the Claude API
        // For now, we'll create a mock response
        
        // This is where you would integrate with your Claude API client
        // Example:
        // let response = claude_client
        //     .create_message()
        //     .system(&self.system_prompt)
        //     .user(request)
        //     .model(&self.model_config.model)
        //     .temperature(self.model_config.temperature)
        //     .max_tokens(self.model_config.max_tokens)
        //     .send()
        //     .await?;
        
        // For demonstration, return a sample plan
        Ok(json!({
            "goal": request.lines().nth(0).unwrap_or("Unknown goal"),
            "tasks": [
                {
                    "id": "analyze_requirements",
                    "name": "Analyze Requirements",
                    "description": "Parse and understand the requirements",
                    "goal": "Analyze the provided requirements and extract key components",
                    "suggested_agent": "analyst",
                    "expected_inputs": [],
                    "expected_outputs": [
                        {
                            "name": "requirements_analysis",
                            "output_type": "data",
                            "description": "Structured analysis of requirements"
                        }
                    ],
                    "estimated_duration_seconds": 300,
                    "priority": 10,
                    "retriable": true,
                    "success_criteria": ["Requirements fully analyzed and documented"]
                },
                {
                    "id": "implement_solution",
                    "name": "Implement Solution",
                    "description": "Implement the solution based on requirements",
                    "goal": "Create the implementation based on the analyzed requirements",
                    "suggested_agent": "developer",
                    "expected_inputs": [
                        {
                            "name": "requirements_analysis",
                            "input_type": "data",
                            "from_task_id": "analyze_requirements",
                            "description": "The analyzed requirements"
                        }
                    ],
                    "expected_outputs": [
                        {
                            "name": "implementation",
                            "output_type": "file",
                            "description": "The implemented solution"
                        }
                    ],
                    "estimated_duration_seconds": 600,
                    "priority": 8,
                    "retriable": true,
                    "success_criteria": ["Implementation complete and functional"]
                }
            ],
            "dependencies": {
                "implement_solution": ["analyze_requirements"]
            },
            "estimated_duration_seconds": 900,
            "resource_requirements": {
                "peak_memory_gb": 4.0,
                "peak_cpu_cores": 2,
                "total_compute_hours": 0.25
            },
            "success_criteria": ["All tasks completed successfully"],
            "metadata": {
                "confidence_score": 0.85,
                "alternative_approaches": [],
                "risks_and_mitigations": []
            }
        }))
    }

    /// Check if the plan has circular dependencies
    fn has_circular_dependencies(&self, plan: &TaskPlan) -> Result<bool> {
        let mut graph = DiGraph::<String, ()>::new();
        let mut node_indices = HashMap::new();

        // Add all tasks as nodes
        for task in &plan.tasks {
            let idx = graph.add_node(task.id.clone());
            node_indices.insert(task.id.clone(), idx);
        }

        // Add edges for dependencies
        for (task_id, deps) in &plan.dependencies {
            if let Some(&to_idx) = node_indices.get(task_id) {
                for dep in deps {
                    if let Some(&from_idx) = node_indices.get(dep) {
                        graph.add_edge(from_idx, to_idx, ());
                    }
                }
            }
        }

        // Use topological sort to detect cycles
        Ok(toposort(&graph, None).is_err())
    }

    /// Perform topological sort with priority consideration
    fn topological_sort_with_priority(&self, plan: &TaskPlan) -> Result<Vec<String>> {
        let mut graph = DiGraph::<String, ()>::new();
        let mut node_indices = HashMap::new();
        let mut priority_map = HashMap::new();

        // Add all tasks as nodes
        for task in &plan.tasks {
            let idx = graph.add_node(task.id.clone());
            node_indices.insert(task.id.clone(), idx);
            priority_map.insert(task.id.clone(), task.priority);
        }

        // Add edges for dependencies
        for (task_id, deps) in &plan.dependencies {
            if let Some(&to_idx) = node_indices.get(task_id) {
                for dep in deps {
                    if let Some(&from_idx) = node_indices.get(dep) {
                        graph.add_edge(from_idx, to_idx, ());
                    }
                }
            }
        }

        // Perform topological sort
        let topo_order = toposort(&graph, None)
            .map_err(|_| anyhow::anyhow!("Circular dependency detected"))?;

        // Convert back to task IDs, considering priority within each level
        let mut result = Vec::new();
        let mut level_tasks = Vec::new();
        let mut current_depth = 0;

        for node_idx in topo_order {
            let task_id = &graph[node_idx];
            let depth = self.calculate_depth(&graph, node_idx, &node_indices);
            
            if depth > current_depth {
                // Sort tasks at the current level by priority
                level_tasks.sort_by_key(|id: &String| {
                    std::cmp::Reverse(priority_map.get(id).copied().unwrap_or(0))
                });
                result.extend(level_tasks.drain(..));
                current_depth = depth;
            }
            
            level_tasks.push(task_id.clone());
        }

        // Don't forget the last level
        level_tasks.sort_by_key(|id: &String| {
            std::cmp::Reverse(priority_map.get(id).copied().unwrap_or(0))
        });
        result.extend(level_tasks);

        Ok(result)
    }

    /// Calculate the depth of a node in the DAG
    fn calculate_depth(
        &self,
        graph: &DiGraph<String, ()>,
        node: NodeIndex,
        _node_indices: &HashMap<String, NodeIndex>,
    ) -> usize {
        let mut max_depth = 0;
        for edge in graph.edges_directed(node, petgraph::Direction::Incoming) {
            let parent_depth = self.calculate_depth(graph, edge.source(), _node_indices);
            max_depth = max_depth.max(parent_depth + 1);
        }
        max_depth
    }
}

impl Default for PlannerAgent {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_validate_plan_valid() {
        let planner = PlannerAgent::new();
        let plan = TaskPlan {
            goal: "Test goal".to_string(),
            tasks: vec![
                PlannedTask {
                    id: "task1".to_string(),
                    name: "Task 1".to_string(),
                    description: "First task".to_string(),
                    goal: "Do something".to_string(),
                    suggested_agent: "agent1".to_string(),
                    expected_inputs: vec![],
                    expected_outputs: vec![],
                    estimated_duration_seconds: Some(60),
                    priority: 5,
                    retriable: true,
                    success_criteria: vec!["Complete successfully".to_string()],
                },
                PlannedTask {
                    id: "task2".to_string(),
                    name: "Task 2".to_string(),
                    description: "Second task".to_string(),
                    goal: "Do something else".to_string(),
                    suggested_agent: "agent2".to_string(),
                    expected_inputs: vec![],
                    expected_outputs: vec![],
                    estimated_duration_seconds: Some(120),
                    priority: 8,
                    retriable: false,
                    success_criteria: vec!["Complete successfully".to_string()],
                },
            ],
            dependencies: HashMap::from([
                ("task2".to_string(), vec!["task1".to_string()]),
            ]),
            estimated_duration_seconds: Some(180),
            resource_requirements: ResourceRequirements {
                peak_memory_gb: Some(4.0),
                peak_cpu_cores: Some(2),
                total_compute_hours: Some(0.05),
            },
            success_criteria: vec!["All tasks complete".to_string()],
            metadata: PlanMetadata {
                created_at: Utc::now(),
                planner_version: "1.0.0".to_string(),
                confidence_score: 0.9,
                alternative_approaches: vec![],
                risks_and_mitigations: vec![],
            },
        };

        assert!(planner.validate_plan(&plan).is_ok());
    }

    #[test]
    fn test_validate_plan_duplicate_ids() {
        let planner = PlannerAgent::new();
        let mut plan = create_test_plan();
        plan.tasks[1].id = "task1".to_string(); // Duplicate ID

        assert!(planner.validate_plan(&plan).is_err());
    }

    #[test]
    fn test_validate_plan_invalid_dependency() {
        let planner = PlannerAgent::new();
        let mut plan = create_test_plan();
        plan.dependencies.insert("task1".to_string(), vec!["nonexistent".to_string()]);

        assert!(planner.validate_plan(&plan).is_err());
    }

    #[test]
    fn test_circular_dependency_detection() {
        let planner = PlannerAgent::new();
        let mut plan = create_test_plan();
        
        // Create circular dependency: task1 -> task2 -> task1
        plan.dependencies.insert("task1".to_string(), vec!["task2".to_string()]);
        plan.dependencies.insert("task2".to_string(), vec!["task1".to_string()]);

        assert!(planner.has_circular_dependencies(&plan).unwrap());
    }

    fn create_test_plan() -> TaskPlan {
        TaskPlan {
            goal: "Test goal".to_string(),
            tasks: vec![
                PlannedTask {
                    id: "task1".to_string(),
                    name: "Task 1".to_string(),
                    description: "First task".to_string(),
                    goal: "Do something".to_string(),
                    suggested_agent: "agent1".to_string(),
                    expected_inputs: vec![],
                    expected_outputs: vec![],
                    estimated_duration_seconds: Some(60),
                    priority: 5,
                    retriable: true,
                    success_criteria: vec!["Complete successfully".to_string()],
                },
                PlannedTask {
                    id: "task2".to_string(),
                    name: "Task 2".to_string(),
                    description: "Second task".to_string(),
                    goal: "Do something else".to_string(),
                    suggested_agent: "agent2".to_string(),
                    expected_inputs: vec![],
                    expected_outputs: vec![],
                    estimated_duration_seconds: Some(120),
                    priority: 8,
                    retriable: false,
                    success_criteria: vec!["Complete successfully".to_string()],
                },
            ],
            dependencies: HashMap::new(),
            estimated_duration_seconds: Some(180),
            resource_requirements: ResourceRequirements {
                peak_memory_gb: Some(4.0),
                peak_cpu_cores: Some(2),
                total_compute_hours: Some(0.05),
            },
            success_criteria: vec!["All tasks complete".to_string()],
            metadata: PlanMetadata {
                created_at: Utc::now(),
                planner_version: "1.0.0".to_string(),
                confidence_score: 0.9,
                alternative_approaches: vec![],
                risks_and_mitigations: vec![],
            },
        }
    }
}